urls.py
from main.views import (
    Index_View,
    News_View,
    Category_View,
    News_page_View,
    Post_View,
    News_page_get_View,
    Aboutas_View,
    PostViewSet,
    shop_View,
    contact_View,
    login_View,
    search_View,
    Media_View,
    categorylast
    
)
from django.urls import path,include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register("posts", PostViewSet, basename="posts")

urlpatterns = [
    # path("",index,name="index")
    path("",Index_View.as_view(),name="Index_View"),
    path("news/",News_View.as_view(),name="News_View"),
    path("shop/",shop_View,name="shop_View"),
    path("News_page_View/",News_page_View.as_view(),name="News_page_View"),
    path("aboutas/",Aboutas_View.as_view(),name="Aboutas_View"),
    path("contact/",contact_View,name="contact_View"),
    path("search/",search_View.as_view(),name="search_View" ),
    path("Media/",Media_View.as_view(),name="Media_View"),
    path("login_View/",login_View,name="login_View"),
    path("Post_View/<int:id>/",Post_View.as_view(),name="Post_View"),
    path("News_page_get_View/<int:id>/",News_page_get_View,name="News_page_get_View"),
    path("",include(router.urls)),
    path("categorylast/<slug:slug>/",categorylast,name="categorylast"),
    path("<slug:slug>/",Category_View,name="Category_View"),
]

models.py

from django.db import models
from ckeditor.fields import RichTextField
from froala_editor.fields import FroalaField
from django.db.models import Q
from mptt.models import MPTTModel,TreeForeignKey
from PIL import Image 
from io import BytesIO
from django.core.files import File




class ProfileQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (
                        # Q(user__username__icontains=query)|
                        Q(title__icontains=query)
                        
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class PostManager(models.Manager):
    def get_queryset(self):
        return ProfileQuerySet(self.model,using=self._db)
    
    def search(self,query=None):
        return self.get_queryset().search(query=query)






Choicese = [
    ("number","հեռախոսահամար"),
    ("email","Ել․հասցե"),
    ("addres","Հասցե"),
    
]

class Contacts(models.Model):
    name = FroalaField("Մութքագրման դաշտ",max_length=50)
    chois = models.CharField("Տեսակ", choices=Choicese, max_length=15)
    
    def __str__(self):
       return self.name
   
    class Meta:
        
        verbose_name = 'Տվյալ'
        verbose_name_plural = 'Տվյալներ'
  
  
SocialChoicese = [
    ("facebook","facebook"),
    ("instagram","instagram"),
    ("telegarm","telegarm"),
    
]      
        
class socialmedia(models.Model):
    name = models.URLField("URL-հասցե")
    chois = models.CharField("Ցանկ",max_length=15,choices=SocialChoicese)
    
    def __str__(self):
        return self.name
    
    class  Meta:
        
        verbose_name = 'Սոցցանց'
        verbose_name_plural = 'Սոցցանցեր'
    
    
class slide(models.Model):
    
    slide = models.ImageField(upload_to="slide")
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.slide = new_image
        super().save(*args, **kwargs)
    
    class Meta:
      
        verbose_name = 'Սլայդ'
        verbose_name_plural = 'Սլայդներ'
    
class Welcom(models.Model):
    title = models.CharField("վերնագր",max_length=68)
    text = RichTextField("տեքստ")
    image = models.ImageField("Նկար",upload_to="Welcom")
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Գլխաոր"
        verbose_name_plural = "Գլխաոր"
    
class Doctors(models.Model):
    title = models.CharField("Անուն",max_length=100)
    categoris = models.CharField("մասնագիտություն",max_length=100)
    image = models.ImageField("նկար",upload_to="Doctors")
    text = RichTextField("նկարագիր")
    
    objects = PostManager()
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Բժիշկ"
        verbose_name_plural = "Բժիշկներ"

   
    
class category(models.Model):
    title = models.CharField("կատեգորյայի-անվանում",max_length=200)
    text = RichTextField("գլխաոր-տեքստ")
    Paragraphtext = models.CharField("յեկրորտական-տքստ",max_length=165)
    file = models.FileField("նկար կամ վիդեո",upload_to="category")
    slug = models.SlugField("URI")

    
    def __str__(self):
        return self.title
    
    class Meta:
                
        verbose_name = 'կատեգորյա'
        verbose_name_plural = 'կատեգորյաներ'
 
class Post(models.Model):
    category = models.ForeignKey(category,on_delete=models.CASCADE, verbose_name="Կատեգորյաներ", related_name="KeyCategori")  
    image = models.FileField("նկար կամ վիդեո",upload_to="Post")   
    title = models.CharField("նյութի վերնագիր",max_length=100)
    text = RichTextField("Նյութի բովանդակություն")
    doctory = models.ForeignKey(Doctors,on_delete=models.CASCADE, verbose_name="բժիշկը", related_name="KeyDoctots")
    data = models.DateTimeField("ժամանակ",auto_now_add=True)
    rec = models.BooleanField("գլխաոր-նյութում",default=False)
    
    objects = PostManager()

    def __str__(self):
        return self.title
    
    
    class Meta:
       
        verbose_name = 'Գլախաոր-Փոստ'
        verbose_name_plural = 'Գլախաոր-Փոստ'
      
      
class Comment(MPTTModel):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    parent = TreeForeignKey("self",on_delete=models.CASCADE,null=True,blank=True,related_name='children')

    name = models.CharField("Անվանում",max_length=24)
    message = models.TextField("մաեկնաբանություն")
    image = models.ImageField("նակար",upload_to="comment",null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    button = models.BooleanField("Հաստատել",default=False)
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)
    
    class MPTTMeta:
        order_insertion_by = ['name']
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Կոմենտ'
        verbose_name_plural = 'Կոմենտներ'
        
    
class ShopCategory(models.Model):
    
    title = models.CharField("կատեգորյա",max_length=100)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Ապրանքիկատեգորյա'
        verbose_name_plural = 'Ապրանքիկատեգորյաներ'
        
class shop(models.Model):
    
    title = models.CharField("վերնագիր",max_length=17)
    category = models.ForeignKey(ShopCategory,related_name="comments",on_delete=models.CASCADE)
    price = models.SmallIntegerField("արժեք")
    image = models.ImageField("Նկար",upload_to="shop")
    objects = PostManager()
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    
    class Meta:
        verbose_name = 'Ապրանք'
        verbose_name_plural = 'Ապրանքներ'
  
textchoise = [
    ("0","news"),
    ("1","shop"),
    
]      
class pagetext(models.Model):
    
    
        
    categoryi = models.CharField("նշեք էջը",choices=textchoise,max_length=100)
    texti = RichTextField()
    
    def __str__(self):
        return self.categoryi
    
    
    class Meta:
        verbose_name = "Էջի մեկնաբանություն"
        verbose_name_plural = "Էջի մեկնաբանություներ"
        
class video(models.Model):
    
    video = models.URLField("URL")
    
    def __str__(self):
        return self.video
    
    class Meta:
        verbose_name="Մեդիա"
        verbose_name_plural = "Մեդիա"
        
        
class categoryfirst(models.Model):
    title = models.CharField("Վերնագիր",max_length=100)
    text = RichTextField("տեքստ")
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField("նկար",upload_to="categoryfirst")
    slug = models.SlugField()
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Գլղավոր-Կատեգորյ"
        verbose_name_plural = "Գլղավոր-Կատեգորյաներ" 
        
        
class CategoryLast(models.Model):
    title = models.CharField("Վերնագիր",max_length=100)
    text = RichTextField("տեքստ")
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField("նկար",upload_to="categoryfirst")
    keylast = models.ForeignKey(categoryfirst,on_delete=models.CASCADE,related_name="kategorykey")
           
    def __str__(self):
        
        return self.title
    
    def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)
        
    
    class Meta:
        verbose_name = "Յեկրերթական-Կատեգորյա"
        verbose_name_plural ="Յեկրերթական-Կատեգորյանոր "
    
    
def compress(image):
    im = Image.open(image)
    im_io = BytesIO() 
    im.save(im_io, 'JPEG', quality=50) 
    new_image = File(im_io, name=image.name)
    return new_image

templates/mainapp/Doctors.html
{% extends 'base.html' %}

{% block main %}
{% load i18n %}
<div class="page-banner overlay-dark bg-image" style="background-image: url(
  {% for a in slidecontext  %}
 {{ a.slide.url }}
{% endfor %}
);">

 <div class="banner-section">
   <div class="container text-center wow fadeInUp">
     <nav aria-label="Breadcrumb">
       <ol class="breadcrumb breadcrumb-dark bg-transparent justify-content-center py-0 mb-2">
         <li class="breadcrumb-item"><a href="{% url 'Index_View' %}">{% trans "գլխաոր" %}</a></li>
         <li class="breadcrumb-item active" aria-current="page">{% trans "բժիշկներ" %}</li>
       </ol>
     </nav>
     <h1 class="font-weight-normal">{% trans "բժիշկներ" %}</h1>
   </div> <!-- .container -->
 </div> <!-- .banner-section -->
</div> <!-- .page-banner -->


<div class="page-section pt-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <nav aria-label="Breadcrumb">
            <ol class="breadcrumb bg-transparent py-0 mb-5">
              <li class="breadcrumb-item"><a href="{% url 'Index_View' %}">{% trans "Home" %}</a></li>
              <li class="breadcrumb-item"><a href="{% url "News_page_View" %}">{% trans "Blog" %}</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ doctury.title }}</li>
            </ol>
          </nav>
        </div>
      </div> <!-- .row -->

      <div class="row">
        <div class="col-lg-8">
          <article class="blog-details">
            <div class="post-thumb">
              <img src="{{ doctury.image.url }}" alt="">
            </div>
            <div class="post-meta">
              <div class="post-author">
                <span class="text-grey">{{ doctury.title }}</span> 
              </div>
              <span class="divider">|</span>
             
              <div>
                {% for Doc in Doctors %}
                <a href="{% url 'doctors_view'  id=Doc.id %}">{{ Doc.title }}</a>
                {% endfor %}

              </div>
             
            </div>
            <h2 class="post-title h1">{{ doctury.title }}</h2>
            <div class="post-content">
              <p>{{ doctury.text|safe }}</p>

            </div>

          </article> <!-- .blog-details -->

        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            {% include "mainapp/includes/inchlude.html" %}
        


          </div>
        </div> 
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .page-section -->



{% endblock main %}



templates/mainapp/aboutas.html
{% extends 'base.html' %}


{% block main %}

<div class="page-banner overlay-dark bg-image" style="background-image: url(
  {% for a in slidecontext  %}
 {{ a.slide.url }}
{% endfor %}
);">

 <div class="banner-section">
   <div class="container text-center wow fadeInUp">
     <nav aria-label="Breadcrumb">
       <ol class="breadcrumb breadcrumb-dark bg-transparent justify-content-center py-0 mb-2">
         <li class="breadcrumb-item"><a href="{% url 'Index_View' %}">Home</a></li>
         <li class="breadcrumb-item active" aria-current="page">About</li>
       </ol>
     </nav>
     <h1 class="font-weight-normal">About</h1>
   </div> <!-- .container -->
 </div> <!-- .banner-section -->
</div> <!-- .page-banner -->
<link rel="apple-touch-icon" href= "assets/img/apple-icon.png">

{% comment %} <div class="page-section banner-home bg-image" style="background-image: url(../assets/img/banner-pattern.svg);">
    <div class="container py-2 py-lg-0">
        <br>
      <div class="row align-items-center">
        <div class="col-lg-9 wow fadeInRight">
          <h1 class="font-weight-normal mb-5">Get easy access o</h1>
          <a href="#"><img src="../assets/img/google_play.svg" alt=""></a>
          <a href="#" class="ml-2"><img src="../assets/img/app_store.svg" alt=""></a>
        </div>
      </div>
    </div>
  </div>  {% endcomment %}
  
<div class="page-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-secondary text-white">
              <span class="mai-chatbubbles-outline"></span>
            </div>
            <p><span>Chat</span> with a doctors</p>
          </div>
        </div>
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-primary text-white">
              <span class="mai-shield-checkmark"></span>
            </div>
            <p><span>One</span>-Health Protection</p>
          </div>
        </div>
        <div class="col-md-4 py-3 wow zoomIn">
          <div class="card-service">
            <div class="circle-shape bg-accent text-white">
              <span class="mai-basket"></span>
            </div>
            <p><span>One</span>-Health Pharmacy</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-section">
    <div class="container">
  <div class="col-md-12 col-lg-12 pb-12">
    <div class="h-100 py-5 services-icon-wap shadow">
        <div class="h1 text-success text-center"><i class="fa fa-truck fa-lg"></i></div>
        <div>
        <h2 class="h5 mt-4 text-center">Delivery Services</h2>
        <h2 class="h5 mt-4 text-center">Delivery Services</h2>
        <h2 class="h5 mt-4 text-center">Delivery Services</h2>
        
    
        
</div> 
  
</div>
  </div>
</div>
  <div class="page-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 wow fadeInUp">
          <h1 class="text-center mb-3">{{ v.title }}</h1>
          <div class="text-lg">
            <p>{{ v.text|safe }}</p>
          </div>
        </div>
        <div class="col-lg-10 mt-5">
          <h1 class="text-center mb-5 wow fadeInUp">Our Doctors</h1>
          <div class="row justify-content-center">
           {% for a in Doctors %}
            <div class="col-md-6 col-lg-4 wow zoomIn">
              <div class="card-doctor">
                <div class="header">
                  <img src="{{ a.image.url }}" alt="">
                  <div class="meta">
                    <a href="#"><span class="mai-call"></span></a>
                    <a href="#"><span class="mai-logo-whatsapp"></span></a>
                  </div>
                </div>
                <div class="body">
                  <p class="text-xl mb-0">{{ a.title }}</p>
                  <span class="text-sm text-grey">{{ a.categoris }}</span>
                </div>
              </div>
            </div>
            {% endfor %}


          </div>
        </div>
      </div>
    </div>
  </div>
  <div >
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d763.8835091517292!2d44.490078343078466!3d40.196474551853534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x406abdbc78167d43%3A0xce47f78da9a79b52!2sEstelife%20Clinic!5e0!3m2!1shy!2s!4v1646320372680!5m2!1shy!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>  <div>

          
{% endblock main %}

templates/mainapp/post.html
{% extends 'base.html' %}
{% load humanize %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

{% load mptt_tags %}


{% block main %}

<div class="page-banner overlay-dark bg-image" style="background-image: url(
  {% for a in slidecontext  %}
 {{ a.slide.url }}
{% endfor %}
);">

 <div class="banner-section">
   <div class="container text-center wow fadeInUp">
     <nav aria-label="Breadcrumb">
       <ol class="breadcrumb breadcrumb-dark bg-transparent justify-content-center py-0 mb-2">
         <li class="breadcrumb-item"><a href="{% url 'Index_View' %}">Home</a></li>
         <li class="breadcrumb-item active" aria-current="page">Post</li>
       </ol>
     </nav>
     <h1 class="font-weight-normal">Post</h1>
   </div> <!-- .container -->
 </div> <!-- .banner-section -->
</div> <!-- .page-banner -->

<div class="page-section pt-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <nav aria-label="Breadcrumb">
            <ol class="breadcrumb bg-transparent py-0 mb-5">
              <li class="breadcrumb-item"><a href="{% url 'Index_View' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url 'News_page_View' %}">Blog</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
            </ol>
          </nav>
        </div>
      </div> <!-- .row -->

      <div class="row">
        <div class="col-lg-8">
          <article class="blog-details">
            <div class="post-thumb">
              <img src="{{ post.image.url }}" alt="">
            </div>
            <div class="post-meta">
              <div class="post-author">
                <span class="text-grey">By</span> <a href="#">{{ post.doctory }}</a>  
              </div>
              <span class="divider">|</span>
              <div class="post-date">
                <a href="#">{{ post.data }}</a>
              </div>
              <span class="divider">|</span>
              <div>
                <a href="#">{{ post.category }}</a> 
              </div>
              <span class="divider">|</span>
              <div class="post-comment-count">
                <a href="#">{{ post.comments.all|length }} Comments</a>
              </div>
            </div>
            <h2 class="post-title h1">{{ post.title }}</h2>
            <div class="post-content">
              <p>{{ post.text|safe }}</p>

              {% comment %} <p>Praesent vel mi bibendum, finibus leo ac, condimentum arcu. Pellentesque sem ex, tristique sit amet suscipit in, mattis imperdiet enim. Integer tempus justo nec velit fringilla, eget eleifend neque blandit. Sed tempor magna sed congue auctor. Mauris eu turpis eget tortor ultricies elementum. Phasellus vel placerat orci, a venenatis justo. Phasellus faucibus venenatis nisl vitae vestibulum. Praesent id nibh arcu. Vivamus sagittis accumsan felis, quis vulputate</p> {% endcomment %}
            </div>
            <div class="post-tags">
              <a href="#" class="tag-link">{{ post.category }}</a>
             
            </div>
          </article> <!-- .blog-details -->
          <div class="container mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12">
                    <div class="headings d-flex justify-content-between align-items-center mb-3">
                        <h5>Unread comments({{ post.comments.all|length }})</h5>
                        
                    </div>
                 {% comment %} {% for a in post.comments.all %}
                    {% if a.button %}
                    <div class="card p-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="user d-flex flex-row align-items-center"> <img src="{{ a.image.url }}" width="30" class="user-img rounded-circle mr-2"> <span><small class="font-weight-bold text-primary">{{ a.name }}</small> <small class="font-weight-bold">{{ a.message }}</small></span> </div> <small>2 days ago</small>
                        </div>
                        <div class="action d-flex justify-content-between mt-2 align-items-center">
                            <div class="reply px-4"> <small>Remove</small> <span class="dots"></span> <small>{{ a.name }}</small> <span class="dots"></span> <small>{{ c.message }}</small> </div>
                            <div class="icons align-items-center"> <i class="fa fa-star text-warning"></i> <i class="fa fa-check-circle-o check-icon"></i> </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}  {% endcomment %}
                 {% recursetree post.comments.all %}
                    <div class="card p-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="user d-flex flex-row align-items-center"> <img src="{{ node.image.url }}" width="30" class="user-img rounded-circle mr-2"> <span><small class="font-weight-bold text-primary" id="{{ node.id }}" >{{ node.name }}</small> <small class="font-weight-bold">{{ node.message }}</small></span> </div> <small>{{ node.created_at|naturalday }}</small>
                        </div>
                        <div class="action d-flex justify-content-between mt-2 align-items-center">
                            <div class="reply px-4"> <small onclick="myFunction({{ node.id }})">Remove</small> <span class="dots"></span> <small>{{ node.name }}</small> <span class="dots"></span> <small>{{ node.message }}</small> </div>
                            <div class="icons align-items-center"> <i class="fa fa-star text-warning"></i> <i class="fa fa-check-circle-o check-icon"></i> </div>
                        </div>
                    </div>
                    {% if not node.is_leaf_node %}
                       <ul class="children">
                      {{ children }}
                         </ul>
                      {% endif %}

                    {% endrecursetree %}

                   
                   
                </div>
            </div>
        </div>

          <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Leave a comment</h3>
            {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
            {{ request.user.last_name  }}
            <form method="POST" id="myForm" enctype="multipart/form-data">
                {% csrf_token %}
              {% comment %} <div class="form-row form-group">
                <div class="col-md-6">
                  <label for="name">Name *</label>
                  <input type="text" class="form-control" id="name">
                </div>
                <div class="col-md-6">
                  <label for="email">Email *</label>
                  <input type="email" class="form-control" id="email">
                </div>
              </div> {% endcomment %}
              {{ form.as_p }}

              {% comment %} <div class="form-group">
                <label for="website">Name </label>
                <input type="url" class="form-control" id="website">
              </div>
  
              <div class="form-group">
                <label for="message">Message</label>
                <textarea name="msg" id="message" cols="30" rows="8" class="form-control"></textarea>
              </div> {% endcomment %}
              <div class="form-group">
                <input type="submit" value="Post Comment" class="btn btn-primary">
              </div>
  
            </form>
            {% comment %} {% endif %} {% endcomment %}
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="sidebar-block">
              <h3 class="sidebar-title">Search</h3>
              <form action="#" class="search-form">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                  <button type="submit" class="btn"><span class="icon mai-search"></span></button>
                </div>
              </form>
            </div>
            <div class="sidebar-block">
              <h3 class="sidebar-title">Categories</h3>
              <ul class="categories">
                <li><a href="#">Food <span>12</span></a></li>
                <li><a href="#">Dish <span>22</span></a></li>
                <li><a href="#">Desserts <span>37</span></a></li>
                <li><a href="#">Drinks <span>42</span></a></li>
                <li><a href="#">Ocassion <span>14</span></a></li>
              </ul>
            </div>

            <div class="sidebar-block">
              <h3 class="sidebar-title">Recent Blog</h3>
              {% for rec in recent %}
              <div class="blog-item">
                <a class="post-thumb" href="">
                  <img src="{{ rec.image.url }}" alt="">
                </a>
                <div class="content">
                  <h5 class="post-title"><a href="#">{{ rec.title }}</a></h5>
                  <div class="meta">
                    <a href="#"><span class="mai-calendar"></span> July 12, 2018</a>
                    <a href="#"><span class="mai-person"></span> Admin</a>
                    <a href="#"><span class="mai-chatbubbles"></span> 19</a>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>



            <div class="sidebar-block">
              <h3 class="sidebar-title">Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>
        </div> 
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .page-section -->

  <div class="page-section banner-home bg-image" style="background-image: url(../assets/img/banner-pattern.svg);">
    <div class="container py-5 py-lg-0">
      <div class="row align-items-center">
        <div class="col-lg-4 wow zoomIn">
          <div class="img-banner d-none d-lg-block">
            <img src="../assets/img/mobile_app.png" alt="">
          </div>
        </div>
        <div class="col-lg-8 wow fadeInRight">
          <h1 class="font-weight-normal mb-3">Get easy access of all features using One Health Application</h1>
          <a href="#"><img src="../assets/img/google_play.svg" alt=""></a>
          <a href="#" class="ml-2"><img src="../assets/img/app_store.svg" alt=""></a>
        </div>
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .banner-home -->
<style>


  
    
    .card {
        border: none;
        box-shadow: 5px 6px 6px 2px #e9ecef;
        border-radius: 4px
    }
    
    .dots {
        height: 4px;
        width: 4px;
        margin-bottom: 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block
    }
    
    .badge {
        padding: 7px;
        padding-right: 9px;
        padding-left: 16px;
        box-shadow: 5px 6px 6px 2px #e9ecef
    }
    
    .user-img {
        margin-top: 4px
    }
    
    .check-icon {
        font-size: 17px;
        color: #c3bfbf;
        top: 1px;
        position: relative;
        margin-left: 3px
    }
    
    .form-check-input {
        margin-top: 6px;
        margin-left: -24px !important;
        cursor: pointer
    }
    
    .form-check-input:focus {
        box-shadow: none
    }
    
    .icons i {
        margin-left: 8px
    }
    
    .reply {
        margin-left: 12px
    }
    
    .reply small {
        color: #b7b4b4
    }
    
    .reply small:hover {
        color: green;
        cursor: pointer
    }


</style>

<script>
  function myFunction(id){
    var a = document.getElementById(id);
    a.insertAdjacentHTML("afterend",'<form method="POST" enctype="multipart/form-data">\
      <input type="hidden" name="csrfmiddlewaretoken" value="OOqVE1HwzagaTAvEJBWkJBncI0ZgApei8fsNDmVbRgCrSWPLJ44HpMLxjqVNWx7C">\
      <p><label for="id_name">Անվանում:</label> <input type="text" name="name" maxlength="24" class="form-control" placeholder="Name" required="" id="id_name"></p>\
      <p><label for="id_message">Մաեկնաբանություն:</label> <textarea name="message" cols="40" rows="10" class="form-control" placeholder="Text" required="" id="id_message"></textarea></p>\
      <p><label for="id_image">Նակար:</label> <input type="file" name="image" accept="image/*" required="" id="id_image"></p>\
      <p> <select name="parent" class="d-none" id="id_parent">\
      <option value="'+ id +'" selected="'+ id +'">---------</option>\
      </select></p>\
      <div class="form-group">\
          <input type="submit" value="Post Comment" class="btn btn-primary">\
      </div>\
      </form>')
 }
  $('#myForm').trigger("reset");

</script>


{% endblock main %}